import { 
  StarIcon, 
  PresentationChartLineIcon, 
  ChartBarIcon, 
  BanknotesIcon, 
  ChatBubbleLeftRightIcon,
  ArrowTrendingUpIcon,
  ChatBubbleOvalLeftIcon,
  UserIcon,
  PaperAirplaneIcon,
  ComputerDesktopIcon,
  ShieldCheckIcon,
  ExclamationTriangleIcon,
  DocumentTextIcon,
  MicrophoneIcon,
  UserGroupIcon,
  ChartPieIcon
} from '@heroicons/react/24/outline'

export const Icons = {
  Star: StarIcon,
  Technical: PresentationChartLineIcon,
  Fundamentals: ChartBarIcon,
  Cashflow: BanknotesIcon,
  Sentiment: ChatBubbleLeftRightIcon,
  TrendingUp: ArrowTrendingUpIcon,
  MessageCircle: ChatBubbleOvalLeftIcon,
  User: UserIcon,
  Send: PaperAirplaneIcon,
  Bot: ComputerDesktopIcon,
  Shield: ShieldCheckIcon,
  AlertTriangle: ExclamationTriangleIcon,
  DocumentText: DocumentTextIcon,
  Microphone: MicrophoneIcon,
  UserGroup: UserGroupIcon,
  ChartPie: ChartPieIcon,
  ChartBar: ChartBarIcon,
}
